/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "serial.h"

int main(void) {

//	// EXERCISE 2 - B (RECEIVE + CALLBACK)
//
//	serialInitialise(BAUD_115200, &USART1_PORT, &transmitStringInfo);
//
//	while (1) {
//		receiveString(&USART1_PORT);
//	}

//	// EXERCISE 2 - C (RECEIVE AND TRANSMIT WITH RECEIVE INTERRUPT)
//
//	serialInitialise(BAUD_115200, &USART1_PORT, &transmitStringInfo);
//	serialReceiveInterrupt(&USART1_PORT);


	// Exercise 2 - D (DOUBLE BUFFER BS)

	serialInitialise(BAUD_115200, &USART1_PORT, &transmitStringInfo); //my_rx_callback
	serialReceiveInterrupt(&USART1_PORT);
	serialTransmitInterrupt(&USART1_PORT);

	for(;;);
}
