/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "timer.h"
#include "gpio.h"
#include <stdint.h>

//void resetTimerExample(){
//	resetTIM2(2000);
//}


//  general purpose timer registers page 647
int main(void) {
//    // EXERCISE 3 -----

	enableGPIOClocks();
	enableGPIOELEDS();

//    // Exercise 3 - A
//
//    setTIM2callback(&invertLEDs);
//    init_TIM2(2000);

//    // Exercise 3 - B

	setTIM2callback(&chaseLed);
	init_TIM2(50);
//    resetTIM2(2000);

//	 // HELPS CLARIFYING THE RESET FUNCTIONALITY
//	startOneShotTIM3(10000, &resetTimerExample);

//    // Exercise 3 - C
//
//	setTIM2callback(&chaseLed);
//	init_TIM2(1000);
//
//	startOneShotTIM3(10000, &invertLEDs);

	for(;;);
}


