/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32f303xc.h"
#include "gpio.h"
#include "timer.h"
#include "adc.h"
#include "serial.h"
#include "colour_detector.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif






int main(void)
{
	enableGPIOClocks();
	enableGPIODLEDS();
	serialInitialise(BAUD_115200, &USART1_PORT, 0x00); // remember to change baud rate multiplication if merge to puzzle 1
	initialiseSingleADC();

	//start state machine with a timer callback function
	setTIM2Callback(&handleStateMachine);
	init_TIM2(50); // set timer duration as 50ms


	// PINS
	// PD1 to RED
	// PD2 to GREEN
	// PD3 to BLUE
	// PA1 to LDR circuit (5V -> 2k resistor -> probe -> LDR -> GND)

	while (1){
	}

}




