/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include "gpio.h"
#include "timer.h"

void chaseLed();

int main(void) {
//	// EXERCISE 1 ------

//	// EXERCSIE 1 - B (BUTTON IONTERRUPT CASUES CALLBACK)
//
//	init_main(&chaseLed);

//	// EXERCISE 1 - D (BUTTON INTERRUPT CAUSES ADDING TO PENDING STATE AND TIMER INTERRUPT ISSUES THE PENDING STATE TO GPIOES)
//
//	init_main(&pendingChaseLed);
//
//	init_TIM2(1000);
//	setTIM2callback(&updatePending);

	for(;;);
}


