/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "serial.h"
#include "timer.h"
#include "gpio.h"
#include "integration.h"


int main(void)
{
	// EXERCISE 4 -----

	init_main(0x00);
	enableTIMERClocks();
	enableTimerInterrupt();
	TIM2_IRQHandler();
	SerialInitialise(BAUD_115200, &USART1_PORT, &commandParser);
	serialReceiveInterrupt(&USART1_PORT);
}
